import './globals.css';
import Link from 'next/link';

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body>
        <main className="flex min-h-screen flex-row  ">
          <div className="w-36 shrink-0 bg-slate-500 p-8 flex-col flex pr-6">
            <Link href="/logic-gates">Home</Link>
            <Link href="/logic-gates">Logic Gates</Link>
          </div>
          <div>{children}</div>
        </main>
      </body>
    </html>
  );
}
